run:
  timeout: 5m
  modules-download-mode: readonly
linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - unused
    - typecheck
linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
